@startuml
'https://plantuml.com/class-diagram

package RoomMate{

package WebUI{
    class RoomMateController
}

package domain{

package service{

    interface IWorkspaceRepository{
        + Collection<Workspace> findByTraits(Collection<Trait> traists)
        + Optional<Workspace> findById(Integer id)
    }
    class BookingService{
        + <Workspace>List : allWorkspaces()
        + <Workspace>List : allWorkspaces(Collection<Trait> traists)
    }
    class NotExistentException{
        This handles failed id Searches
    }
    class UnvalidatedInput{
        This handles wrong input
    }

}

    package model{

        class Room{
            - UUID : id
            -String : name
        }

        class Trait{
            -String : name
        }

        class Timespan << Record >> {
            - LocalDate : date
            - LocalTime : startTime
            - LocalTime : endTime
        }


        class Workspace{
            - UUID : id
            - Room : number
            - List<Trait> : traits
            - Set<Timespan> : existingReservations
            + boolean : isOverlap()
        }


    }

}

package DB{

        class WorkspaceRepository{}

}

WorkspaceRepository --> IWorkspaceRepository
}


@enduml