@startuml
'https://plantuml.com/class-diagram

package RoomMate{


package adapter{

    package web{

        class RoomMateController << @Controller >>{
            - BookingService : bookingService
        }

    }

    package db{

        class WorkspaceRepositoryImpl{
            - WorkspaceDao : db
            + Integer : save(Workspace workspace)
            + void : deleteById(Integer id)
            + Optional<Workspace> : findById(Integer id)
            + List<Workspace> : findAll()
        }
        interface WorkspaceDao << extends CrudRepository[Workspace, Integer] >>{
            + Integer : save(WorkspaceDto workspaceDto)
            + void : deleteById(Integer id)
            + Optional<WorkspaceDto> : findById(Integer id)
            + List<WorkspaceDto> : findAll()
        }
        class RoomDto << Record >> {
            - UUID: uuid
            - @Id Integer : id
            - String : name
        }
        class TraitDto << Record >> {
            - @Id Integer : id
            - String : name
        }
        class TimespanDto << Record >> {
            - LocalDate : date
            - LocalTime : startTime
            - LocalTime : endTime
            - Integer : workspaceId
        }
        class WorkspaceDto << Record >> {
            - @Id Integer : id
            - Integer : roomId
            - List<Trait> : traitId
            - Set<Timespan> : existingReservations
        }

    }

    package api{

        class RoomMateApi << @RestController >>{}

    }

    package security{

        class SecurityConfig{}
        class AppUserService{}

    }

}

package domain{

    package service{

        interface WorkspaceRepository{
            + Integer : save(Workspace workspace)
            + void : deleteById(Integer id)
            + Optional<Workspace> : findById(Integer id)
            + List<Workspace> : findAll()
        }
        class BookingService{
            - WorkspaceRepository : repo
            + <Workspace>List : allWorkspaces()
            + <Workspace>List : allWorkspacesByTraits(Collection<Trait> traits)
            + Workspace : getWorkspace(Integer id)
            + void : addTrait(Integer id, String trait)
            + void : addTraits(Integer id, List<Trait> traits)
        }
        class NotExistentException{
            This handles failed id searches
        }
        class UnvalidatedInput{
            This handles wrong input
        }

    }

    package model{

        class Room{
            - UUID : uuid
            - Integer : id
            - String : name
        }
        class Trait{
            - Integer : id
            - String : name
        }
        class Timespan << Record >> {
            - LocalDate : date
            - LocalTime : startTime
            - LocalTime : endTime
            - Integer : workspaceId
        }
        class Workspace{
            - Integer : id
            - Room : number
            - List<Trait> : traits
            - Set<Timespan> : existingReservations
            + boolean : isOverlap(Timespan timespan)
            + boolean : isValid(Timespan timespan)
            + void : roomDtoTransfer(RoomDto dto)
            + void : traitDtoTransfer(TraitDto dto)
            + void : timespanDtoTransfer(TimespanDto dto)
            + void : workspaceDtoTransfer(WorkspaceDto dto)
        }

    }

}

'Adapter - api
RoomMateApi --> BookingService

'Adapter - web
RoomMateController --> BookingService

'Adapter - db
WorkspaceRepositoryImpl ..> WorkspaceRepository
WorkspaceRepositoryImpl --> WorkspaceDao

WorkspaceDto --> TraitDto
WorkspaceDto --> TimespanDto

RoomDto --> WorkspaceRepositoryImpl
TraitDto --> WorkspaceRepositoryImpl
TimespanDto --> WorkspaceRepositoryImpl
WorkspaceDto --> WorkspaceRepositoryImpl

'Domain - Application Service
BookingService --> WorkspaceRepository
BookingService --> NotExistentException
BookingService --> UnvalidatedInput

'Domain - Model
Workspace --> Room
Workspace --> Trait
Workspace --> Timespan

}

@enduml