version: "3.8"
services:
    database:
        image: postgres:16-alpine
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data
        environment:
            - "POSTGRES_DB=jdbc"
            - "POSTGRES_USER=roommate"
            - "POSTGRES_PASSWORD=iamgroot"
