logging:
    level:
        root: warn

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/jdbc
        password: iamgroot
        username: roommate
    flyway:
        locations: classpath:db/migration
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: ${CLIENT_ID}
                        client-secret: ${CLIENT_SECRET}
                        scope: read:public_repo
